#!/bin/bash

# Mount the D drive

MOUNT_POINT="/media/D"

if [ ! -d "$MOUNT_POINT" ]; then
    sudo mkdir "$MOUNT_POINT"
fi

# Warning!! this will destroy any unsaved data that is in the hibernated Windows session
sudo ntfs-3g -o remove_hiberfile /dev/sdb1 "$MOUNT_POINT"
